resources:

  repositories:

    - repository: templates

      type: git

      name: GitTest/templates

      ref: "master"



stages:

  - stage: continuous_integration

    jobs:
    - template: template1.yml@templates
    - job: 
      steps:
      - script: echo Hello, world!
        displayName: 'Run a one-line script'