resources:

  repositories:

    - repository: almtemplates

      type: git

      name: GitTest/templates

      ref: "master"



stages:

  - stage: continuous_integration

    jobs:
    - template: template1.yml@almtemplates
      parameters:
          vmImage: "ABC"
